// Axels släkt - datafil
// Personer, familje-/visningsenheter, relationer och platser.
// Uppdatera helst data här, inte i HTML- eller app-logiken.


const STATUS_LABEL = { confirmed:"Bekräftat", likely:"Starkt sannolikt", working:"Arbetsantagande", open:"Öppet spår" };

const PEOPLE = {
  lars_esbjornsson:{name:"Lars Esbjörnsson",role:"Carls far",status:"confirmed",place:"Tjärby, Grimeton",facts:[["Koppling","Far till Carl Larsson"],["Källa","Carls födelsenotis 1777"]],story:["Lars Esbjörnsson är bekräftad som Carls far i födelsenotisen 1777.","Släktingens dokument pekade sedan tidigare mot Lars Esbjörnsson från Tjärby i Grimeton. Den aktuella födelsenotisens läsning stärker faderskapet."],parents:[],children:["carl_larsson"]},
  inger_jonsdotter:{name:"Inger Jonsdotter",role:"Carls mor",born:"ca 1743",status:"confirmed",place:"Tjärby, Grimeton",facts:[["Ålder i Carls födelsenotis","34 år"],["Koppling","Mor till Carl Larsson"],["Status","Eget ursprung ej färdigkartlagt"]],story:["Inger Jonsdotter är bekräftad som Carls mor i födelsenotisen 1777. Där anges hon som 34 år.","Hennes eget ursprung är ännu inte färdigkartlagt."],parents:[],children:["carl_larsson"]},

  arvid_svensson:{name:"Arvid Svensson",alt:"Arfvid Svensson",role:"Bengtas far",born:"ca 1720-11",died:"1785-02-22",status:"confirmed",place:"Munkaskog, Sven Börges gård, Tvååker",facts:[["Begravd","1785-02-24"],["Hemman","1/2 kronohemman nr 5 Munkaskog"],["Civilstånd vid död","Änkling"],["Ålder i dödnotis","64 år, 3 månader, 11 dagar"],["Dödsorsak","Tolkad som hufvudsjuka / huvudvärkssjuka"],["Bouppteckning","1785-03-22"],["Barn","Hans, Anders, Inger, Bengt, Nils och Bengta"]],story:["Arvid Svensson, även skriven Arfvid Svensson, är Bengtas far enligt födelsenotisen 1774 och är ytterligare stärkt genom bouppteckningen 1785.","Bouppteckningen efter Arfvid Svensson upprättades 22 mars 1785 och gäller mannen på 1/2 kronohemman nr 5 Munkaskog. Den anger barnen med åldrar och binder Bengta till rätt familj och plats.","Boet visar ett etablerat men inte rikt bondehushåll med gårdsdrift, kreatur, textilier, hushållsföremål, bibel och postilla, men även skulder och gravationer."],timeline:[["ca 1720-11","Född, beräknat från ålder i dödnotis."],["1774-10-20","Dottern Bengta föds i Munkaskog."],["1785-02-22","Dör som änkling i Munkaskog, Sven Börges/Sven Börjes gård."],["1785-02-24","Begravs."],["1785-03-22","Bouppteckning upprättas efter Arfvid Svensson."]],parents:[],children:["hans_arfvidsson","anders_arfvidsson","inger_arfvidsdotter","bengt_arfvidsson","nils_arfvidsson","bengta_arvidsdotter"]},
  elin_bengtsdotter:{name:"Elin Bengtsdotter",role:"Bengtas mor",born:"ca dec 1732 / jan 1733",died:"1779-03-28",status:"confirmed",place:"Munkaskog, Sven Börges gård, Tvååker",facts:[["Begravd","1779-04-01"],["Civilstånd vid död","Gift"],["Make","Arfvid / Arvid Svensson"],["Ålder i dödnotis","46 år, 3 månader"],["Dödsorsak","Bröstsjuka"],["Koppling","Mor till Bengta Arvidsdotter"]],story:["Elin Bengtsdotter är bekräftad som Bengtas mor i födelsenotisen 1774.","Dödnotisen anger henne som åboen Arfvid Svenssons hustru i Munkaskog, Sven Börges/Sven Börjes gård. Detta stärker familjegruppen i samma gårdsmiljö.","Elins eget ursprung är ännu inte löst. Nästa steg är att hitta vigseln med Arfvid eller spåra barnens födelsenotiser och faddrar."],timeline:[["ca 1732/1733","Född, beräknat från ålder i dödnotis."],["1774-10-20","Dottern Bengta föds."],["1779-03-28","Dör i Munkaskog, dödsorsak bröstsjuka."],["1779-04-01","Begravs."]],parents:[],children:["hans_arfvidsson","anders_arfvidsson","inger_arfvidsdotter","bengt_arfvidsson","nils_arfvidsson","bengta_arvidsdotter"]},
  hans_arfvidsson:{name:"Hans Arfvidsson",born:"ca 1755",status:"confirmed",role:"Syskon till Bengta",facts:[["Ålder 1785","30 år"],["Källa","Bouppteckning efter Arfvid Svensson 1785"],["Kommentar","Myndig son"]],story:["Hans anges som 30-årig son i bouppteckningen efter Arfvid Svensson i Munkaskog 1785."],parents:["arvid_svensson","elin_bengtsdotter"],children:[]},
  anders_arfvidsson:{name:"Anders Arfvidsson",born:"ca 1760/1761",status:"confirmed",role:"Syskon till Bengta",facts:[["Ålder 1785","24 år"],["Källa","Bouppteckning efter Arfvid Svensson 1785"],["Kommentar","Myndig son"]],story:["Anders anges som 24-årig son i bouppteckningen efter Arfvid Svensson i Munkaskog 1785."],parents:["arvid_svensson","elin_bengtsdotter"],children:[]},
  inger_arfvidsdotter:{name:"Inger Arfvidsdotter",born:"ca 1764/1765",status:"confirmed",role:"Syskon till Bengta",facts:[["Ålder 1785","20 år"],["Källa","Bouppteckning efter Arfvid Svensson 1785"]],story:["Inger anges som 20-årig dotter i bouppteckningen efter Arfvid Svensson i Munkaskog 1785."],parents:["arvid_svensson","elin_bengtsdotter"],children:[]},
  bengt_arfvidsson:{name:"Bengt Arfvidsson",born:"ca 1768/1769",status:"confirmed",role:"Syskon till Bengta",facts:[["Ålder 1785","16 år"],["Källa","Bouppteckning efter Arfvid Svensson 1785"],["Kommentar","Kan vara samma Bengt som tidigare nämnts som broder Bengt i husförhörsspår"]],story:["Bengt anges som 16-årig son i bouppteckningen efter Arfvid Svensson. Han kan vara relevant för tidigare spår där en broder Bengt nämns."],parents:["arvid_svensson","elin_bengtsdotter"],children:[]},
  nils_arfvidsson:{name:"Nils Arfvidsson",alt:"Nils Arvidsson",born:"ca 1770/1771",status:"confirmed",role:"Syskon till Bengta",facts:[["Ålder 1785","14 år"],["Källa","Bouppteckning efter Arfvid Svensson 1785"],["Kommentar","Möjlig koppling till tidigare Nils-spår i Munkaskog"]],story:["Nils anges som 14-årig son i bouppteckningen efter Arfvid Svensson. Detta ger tydligare kontext åt det tidigare Nils-spåret i Munkaskog."],parents:["arvid_svensson","elin_bengtsdotter"],children:[]},

  carl_larsson:{name:"Carl Larsson",role:"Anfader i ledet",born:"1777-11-26",died:"ca 1865",status:"confirmed",place:"Rönås, Tvååker",facts:[["Döpt","1777-11-27"],["Födelseplats","Tjärby, Grimeton"],["Yrke","Dräng, saltsjöfiskare, undantagsman"],["Vigsel","1806-03-08, Tvååker (28 år)"]],story:["Carl föds 26 november 1777 i Tjärby, Grimeton och döps dagen efter. Födelsenotisen anger fadern Lars Esbjörnsson och modern Inger Jonsdotter.","Vid vigseln 1806 står han som dräng i Rönås och anges vara 28 år. Senare återkommer han i Tvååker/Rönås/Ågård-spåret och arbetar bland annat som saltsjöfiskare.","En dödboksnotis 1865 nämner Carl Larsson, undantagsman i Ågård, med ålderdom som dödsorsak."],timeline:[["1777-11-26","Föds i Tjärby, Grimeton."],["1777-11-27","Döps."],["1806-03-08","Gifter sig med Bengta Arvidsdotter."],["1806-04-15","Sonen Anders föds."],["1865","Trolig död som undantagsman i Ågård."]],parents:["lars_esbjornsson","inger_jonsdotter"],children:["anders_carlsson","nils_carlsson","anna_lena_carlsdotter"]},
  bengta_arvidsdotter:{name:"Bengta Arvidsdotter",alt:"Arfvidsdotter",role:"Anmoder i ledet",born:"1774-10-20",status:"confirmed",place:"Munkaskog, Tvååker",facts:[["Döpt","1774-10-23"],["Plats","Munkaskog, Sven Börges gård"],["Vigsel","Piga i Munkaskog (31 år)"],["Bouppteckning","Nämns som 10-årig dotter i Arfvid Svenssons bouppteckning 1785-03-22"],["Syskon","Hans, Anders, Inger, Bengt och Nils"],["Bedömning","Mycket starkt underlag för identifikationen"]],story:["Bengta föds 20 oktober 1774 och döps tre dagar senare på Sven Börges gård i Munkaskog. Föräldrarna anges som Arfvid/Arvid Svensson och Elin Bengtsdotter.","Bouppteckningen efter Arfvid Svensson 1785 räknar upp en dotter Bengta som 10 år gammal. Det passar mycket väl med Bengta född 1774-10-20 och gör identifikationen mycket stark.","Bengta blev moderlös 1779 och faderlös 1785. Hon växte sannolikt upp i ett etablerat men inte rikt bondhushåll på 1/2 kronohemman nr 5 Munkaskog.","Vid vigseln 1806 är hon piga i Munkaskog och anges vara 31 år."],timeline:[["1774-10-20","Föds i Munkaskog, Sven Börges gård."],["1774-10-23","Döps."],["1779-03-28","Modern Elin dör."],["1785-02-22","Fadern Arfvid dör."],["1785-03-22","Nämns som 10-årig dotter i bouppteckningen."],["1806-03-08","Gifter sig med Carl Larsson."]],parents:["arvid_svensson","elin_bengtsdotter"],children:["anders_carlsson","nils_carlsson","anna_lena_carlsdotter"]},
  nils_carlsson:{name:"Nils Carlsson",born:"1809-04-09",status:"confirmed",role:"Syskon",story:["Syskon till Anders, fött 9 april 1809. Grenen är ännu inte utforskad."],parents:["carl_larsson","bengta_arvidsdotter"],children:[]},
  anna_lena_carlsdotter:{name:"Anna Lena Carlsdotter",born:"1814-10-13",status:"confirmed",role:"Syskon",story:["Syskon till Anders, född 13 oktober 1814. Grenen är ännu inte utforskad."],parents:["carl_larsson","bengta_arvidsdotter"],children:[]},

  anders_carlsson:{name:"Anders Carlsson",role:"Direkt linje",born:"1806-04-15",status:"confirmed",place:"Rönås, Tvååker",facts:[["Döpt","1806-04-16"],["Yrke","Dräng, tillträdande åbo"],["Vigsel","1834-12-30, No 5 Munkaskog"]],story:["Anders föds 15 april 1806 i Tvååker som son till Carl Larsson och Bengta Arvidsdotter.","Han står i husförhörslängderna med föräldrarna fram till omkring 1825 och arbetar sedan som dräng på bland annat Munkaskog och Lilla Wråen.","1834 gifter han sig med Johanna Svensdotter och tillträder som åbo i No 5 Munkaskog. Sonen Johan, född 1849, för linjen vidare."],timeline:[["1806-04-15","Föds i Tvååker."],["1806-04-16","Döps."],["ca 1825","Lämnar föräldrahemmet och börjar arbeta som dräng."],["1825-1834","Dräng på bland annat Munkaskog och Lilla Wråen."],["1834-12-30","Gifter sig med Johanna Svensdotter."],["1849-02-15","Sonen Johan Andersson föds."]],parents:["carl_larsson","bengta_arvidsdotter"],children:["lars_august","sven_johan_andersson","christina_andersdotter","bengt_aron_andersson","johan_andersson"]},
  johanna_svensdotter:{name:"Johanna Svensdotter",role:"Maka",born:"1808-01-12",status:"confirmed",place:"Munkaskog",facts:[["Vigsel","Piga i No 5 Munkaskog (1834)"],["Föräldrar","Äldre linje ej färdigkartlagd"]],story:["Johanna föds 12 januari 1808 enligt senare uppgifter. Vid vigseln 1834 är hon piga i No 5 Munkaskog.","Hennes äldre föräldralinje är ännu inte färdigkartlagd och bör utforskas separat."],parents:[],children:["lars_august","sven_johan_andersson","christina_andersdotter","bengt_aron_andersson","johan_andersson"]},
  lars_august:{name:"Lars August",born:"1834-11-04",status:"working",role:"Möjligt syskon",facts:[["Obs","Bör kontrolleras i originalbild"]],story:["Möjligt barn enligt register, fött 1834. Bör bekräftas i originalbild."],parents:["anders_carlsson","johanna_svensdotter"],children:[]},
  sven_johan_andersson:{name:"Sven Johan Andersson",born:"1835-04-03",status:"confirmed",role:"Syskon",story:["Sven Johan föds 3 april 1835 inom äktenskapet. Johanna var sannolikt gravid vid vigseln 1834."],parents:["anders_carlsson","johanna_svensdotter"],children:[]},
  christina_andersdotter:{name:"Christina",born:"1841-08-04",status:"working",role:"Syskon",facts:[["Obs","Bör kontrolleras i originalbild"]],story:["Syskon fött 1841, bör kontrolleras i originalbild."],parents:["anders_carlsson","johanna_svensdotter"],children:[]},
  bengt_aron_andersson:{name:"Bengt Aron",born:"1845-10-24",status:"working",role:"Syskon",facts:[["Obs","Bör kontrolleras i originalbild"]],story:["Syskon fött 1845, bör kontrolleras i originalbild."],parents:["anders_carlsson","johanna_svensdotter"],children:[]},

  johan_andersson:{name:"Johan Andersson",role:"Direkt linje",born:"1849-02-15",status:"confirmed",place:"Tvååker",facts:[["Vigsel","1874-09-11, dräng i Grytås"],["Boende","Morups Prästgård / Skillingshagen"]],story:["Johan föds 15 februari 1849 i Tvååker, son till Anders Carlsson och Johanna Svensdotter.","Vid vigseln 1874 står han som dräng i Grytås. Familjen bor senare vid Morups Prästgård och Skillingshagen."],parents:["anders_carlsson","johanna_svensdotter"],children:["augusta_charlotta","birger_johansson","jenny_johansson","karl_hjalmar_johansson"]},
  britta_lovisa:{name:"Britta Lovisa Carlsdotter",alt:"Karlsdotter",role:"Maka",born:"1849-05-16",status:"confirmed",place:"trol. Tvååker",facts:[["Vigsel","Piga, trol. Långås No 3"],["Föräldrar","Ej kartlagda i denna linje ännu"]],story:["Britta Lovisa föds 16 maj 1849, troligen i Tvååker. Vid giftet är hon piga, troligen i Långås No 3."],parents:[],children:["augusta_charlotta","birger_johansson","jenny_johansson","karl_hjalmar_johansson"]},
  augusta_charlotta:{name:"Augusta Charlotta",born:"1881-12-19",status:"confirmed",role:"Syskon",story:["Syskon fött 1881. Grenen är ännu inte utforskad."],parents:["johan_andersson","britta_lovisa"],children:[]},
  birger_johansson:{name:"Birger",born:"1884-02-13",status:"confirmed",role:"Syskon",story:["Syskon fött 1884. Grenen är ännu inte utforskad."],parents:["johan_andersson","britta_lovisa"],children:[]},
  jenny_johansson:{name:"Jenny",born:"1886-12-22",status:"confirmed",role:"Syskon",story:["Syskon fött 1886. Grenen är ännu inte utforskad."],parents:["johan_andersson","britta_lovisa"],children:[]},

  karl_hjalmar_johansson:{name:"Karl Hjalmar Johansson",role:"Direkt linje",born:"1889-06-07",status:"confirmed",place:"Morup",facts:[["Boende","Morup No 5, Skillingshagen"]],story:["Karl Hjalmar föds 7 juni 1889 i Morup, son till Johan Andersson och Britta Lovisa. Hushållet finns vid Morup No 5, Skillingshagen.","Han och Ester Viktoria får sju kända barn, däribland Karin Margit."],parents:["johan_andersson","britta_lovisa"],children:["asta_linnea","elsa_ingegerd","karin_margit","erik_bertil","gosta_ingemar","karl_john_uno","sjunne_lennart"]},
  ester_viktoria:{name:"Ester Viktoria Johansson",role:"Maka",born:"1898-06-10",status:"confirmed",facts:[["Hushåll","Bekräftad med Karl Hjalmar"],["Föräldrar","Ej kartlagda i denna linje ännu"]],story:["Ester Viktoria föds 10 juni 1898 och är bekräftad i hushållet tillsammans med Karl Hjalmar."],parents:[],children:["asta_linnea","elsa_ingegerd","karin_margit","erik_bertil","gosta_ingemar","karl_john_uno","sjunne_lennart"]},
  asta_linnea:{name:"Asta Linnéa",born:"1924-11-10",status:"confirmed",role:"Syskon",story:["Syskon fött 1924. Grenen är ännu inte utforskad."],parents:["karl_hjalmar_johansson","ester_viktoria"],children:[]},
  elsa_ingegerd:{name:"Elsa Ingegerd",born:"1926",status:"working",role:"Syskon",facts:[["Obs","Datum 1926-05-04 eller 1926-04-05, dubbelkontrollera"]],story:["Syskon fött 1926. Födelsedatumet anges på två sätt och bör dubbelkontrolleras."],parents:["karl_hjalmar_johansson","ester_viktoria"],children:[]},
  erik_bertil:{name:"Erik Bertil",born:"1930-09-30",status:"confirmed",role:"Syskon",story:["Syskon fött 1930. Grenen är ännu inte utforskad."],parents:["karl_hjalmar_johansson","ester_viktoria"],children:[]},
  gosta_ingemar:{name:"Gösta Ingemar",born:"1933-02-07",status:"confirmed",role:"Syskon",story:["Syskon fött 1933. Grenen är ännu inte utforskad."],parents:["karl_hjalmar_johansson","ester_viktoria"],children:[]},
  karl_john_uno:{name:"Karl John Uno",born:"1936-07-25",status:"confirmed",role:"Syskon",story:["Syskon fött 1936. Grenen är ännu inte utforskad."],parents:["karl_hjalmar_johansson","ester_viktoria"],children:[]},
  sjunne_lennart:{name:"Sjunne Lennart",born:"1939-10-30",status:"confirmed",role:"Syskon",story:["Syskon fött 1939. Grenen är ännu inte utforskad."],parents:["karl_hjalmar_johansson","ester_viktoria"],children:[]},

  karin_margit:{name:"Karin Margit Johansson",alt:"g. Bengtsson",role:"Huvudperson",born:"1929-02-10",died:"2022-10-05",status:"confirmed",place:"Morup",facts:[["Liv","Flyttade till Klastorp på 1950-talet"],["Avliden","2022-10-05 enligt dödsannons"]],story:["Karin Margit föds 10 februari 1929 i Morup. Hon bär flicknamnet Johansson och tar som gift namnet Bengtsson.","På 1950-talet flyttar hon med Harry Bengtsson till Klastorp. Tillsammans får de barnen Ingemar och Gerd.","Karin avlider 5 oktober 2022 enligt dödsannons."],timeline:[["1929-02-10","Föds i Morup."],["1950-talet","Flyttar med Harry Bengtsson till Klastorp."],["2022-10-05","Avlider enligt dödsannons."]],parents:["karl_hjalmar_johansson","ester_viktoria"],children:["ingemar_bengtsson","gerd_bengtsson"]},
  harry_bengtsson:{name:"Harry Bengtsson",role:"Make",born:"1916-12-22",died:"1998",status:"confirmed",place:"Klastorp",facts:[["Barn","Ingemar och Gerd Bengtsson"],["Föräldrar","Ej kartlagda i denna linje ännu"]],story:["Harry föds 22 december 1916 i Klastorp och avlider 1998."],parents:[],children:["ingemar_bengtsson","gerd_bengtsson"]},
  ingemar_bengtsson:{name:"Ingemar Bengtsson",status:"confirmed",role:"Barn",story:["Son till Karin och Harry. Grenen är ännu inte utforskad."],parents:["karin_margit","harry_bengtsson"],children:[]},
  gerd_bengtsson:{name:"Gerd Bengtsson",born:"1958-08-06",status:"confirmed",role:"Barn",facts:[["Make","Göran Nilsson"],["Barn","Axel och Ebba"]],story:["Gerd föds 6 augusti 1958, dotter till Karin och Harry.","Gerd gifter sig med Göran Nilsson. Tillsammans får de två barn: Axel och Ebba."],parents:["karin_margit","harry_bengtsson"],children:["axel_nilsson","ebba_nilsson"]},
  goran_nilsson:{name:"Göran Nilsson",role:"Far",born:"1956-05-26",status:"confirmed",facts:[["Maka","Gerd Bengtsson"],["Barn","Axel och Ebba"],["Mor","Elsa Helena"]],story:["Göran Nilsson föds 26 maj 1956. Han är gift med Gerd Bengtsson och tillsammans får de barnen Axel och Ebba.","På pappas sida är hans mor Elsa Helena, född 24 september 1920 i Torpa."],parents:["elsa_helena_karlsson"],children:["axel_nilsson","ebba_nilsson"]},

  elsa_helena_karlsson:{name:"Elsa Helena",role:"Farmor",born:"1920-09-24",status:"confirmed",place:"Balg nr 3, Torpa",facts:[["Födelseförsamling","Torpa (N)"],["Bostad i barndomen","Balg nr 3, Torpa"],["Tvilling","Karin Linnea"],["Källa","Torpa (N) CI:5 (1917-1944), Bild 110, Sida 7, födelsenotis nr 10"]],story:["Elsa Helena är Göran Nilssons mor och därmed farmor på Axels fars sida.","Hon föds 24 september 1920 i Torpa och återfinns i familjen på Balg nr 3. Födelsenotisen anger föräldrarna Karl Karlsson och Elemina Karlsdotter.","Elsa Helena är tvilling med Karin Linnea."],timeline:[["1920-09-24","Föds i Torpa."],["1920","Familjen bor på Balg nr 3 i Torpa."]],parents:["karl_karlsson","elemina_karlsdotter"],children:["goran_nilsson"]},
  karl_karlsson:{name:"Karl Karlsson",alt:"Carl Karlsson",role:"Elsas far",born:"1884-07-13",status:"confirmed",place:"Balg nr 3, Torpa",facts:[["Döpt","1884-07-18"],["Födelseförsamling","Torpa"],["Yrke/titel","Hemmansägare/hemmansbrukare, behöver verifieras"],["Vigsel","troligen 1914-07-03, behöver verifieras"],["Källa","Torpa födelsebok 1884 och hushållssida för Balg nr 3"]],story:["Karl Karlsson, även skriven Carl, föds 13 juli 1884 i Torpa och döps 18 juli.","Födelsenotisen anger föräldrarna Carl Bengtsson och Inger Kristina Nilsdotter på Balg nr 3.","Som vuxen återfinns Karl på Balg nr 3 tillsammans med hustrun Elemina Karlsdotter och barnen Nils Lennart, Ingrid Svea Viola, Elsa Helena, Karin Linnea och Sonja Ingeborg."],timeline:[["1884-07-13","Föds i Torpa."],["1884-07-18","Döps."],["1914-07-03","Trolig vigsel med Elemina Karlsdotter, datum behöver verifieras."],["ca 1916","Familjen flyttar/får flyttningsbetyg till Åby enligt arbetsläsning, behöver verifieras."],["1920","Familjen finns på Balg nr 3 när Elsa Helena föds."]],parents:["carl_bengtsson","inger_kristina_nilsdotter"],children:["nils_lennart_karlsson","ingrid_svea_viola_karlsson","elsa_helena_karlsson","karin_linnea_karlsson","sonja_ingeborg_karlsson"]},
  elemina_karlsdotter:{name:"Elemina Karlsdotter",role:"Elsas mor",born:"1889-07-31",status:"confirmed",place:"Ås / Balg nr 3, Torpa",facts:[["Födelseförsamling","Ås"],["Vigsel","troligen 1914-07-03 med Karl Karlsson, behöver verifieras"],["Bostad omkring 1920","Balg nr 3, Torpa"],["Nästa steg","Kontrollera födelsenotis i Ås 1889 och identifiera föräldrar"]],story:["Elemina Karlsdotter föds 31 juli 1889 i Ås enligt församlingsbokssidan.","Hon är gift med Karl Karlsson och återfinns som mor i hushållet på Balg nr 3 i Torpa."],parents:[],children:["nils_lennart_karlsson","ingrid_svea_viola_karlsson","elsa_helena_karlsson","karin_linnea_karlsson","sonja_ingeborg_karlsson"]},
  nils_lennart_karlsson:{name:"Nils Lennart Karlsson",role:"Syskon till Elsa",born:"1914-07-05",status:"confirmed",place:"Ås",facts:[["Födelseförsamling","Ås"],["Källa","Församlingsbok/husförhörssida för Balg nr 3, sida 34"]],story:["Nils Lennart är son till Karl Karlsson och Elemina Karlsdotter, född 5 juli 1914 i Ås."],parents:["karl_karlsson","elemina_karlsdotter"],children:[]},
  ingrid_svea_viola_karlsson:{name:"Ingrid Svea Viola Karlsson",role:"Syskon till Elsa",born:"1916-04-04",status:"confirmed",place:"Åby",facts:[["Födelseförsamling","Åby"],["Källa","Församlingsbok/husförhörssida för Balg nr 3, sida 34"]],story:["Ingrid Svea Viola är dotter till Karl Karlsson och Elemina Karlsdotter, född 4 april 1916 i Åby."],parents:["karl_karlsson","elemina_karlsdotter"],children:[]},
  karin_linnea_karlsson:{name:"Karin Linnea Karlsson",role:"Tvilling till Elsa",born:"1920-09-24",status:"confirmed",place:"Torpa",facts:[["Födelseförsamling","Torpa"],["Tvilling","Elsa Helena"],["Källa","Församlingsbok/husförhörssida för Balg nr 3, sida 34"]],story:["Karin Linnea är dotter till Karl Karlsson och Elemina Karlsdotter. Hon föds 24 september 1920 i Torpa och är tvilling med Elsa Helena."],parents:["karl_karlsson","elemina_karlsdotter"],children:[]},
  sonja_ingeborg_karlsson:{name:"Sonja Ingeborg Karlsson",role:"Syskon till Elsa",born:"1923-05-20",status:"confirmed",place:"Torpa",facts:[["Födelseförsamling","Torpa"],["Källa","Församlingsbok/husförhörssida för Balg nr 3, sida 34"]],story:["Sonja Ingeborg är dotter till Karl Karlsson och Elemina Karlsdotter, född 20 maj 1923 i Torpa."],parents:["karl_karlsson","elemina_karlsdotter"],children:[]},

  carl_bengtsson:{name:"Carl Bengtsson",role:"Karl Karlssons far",born:"1848-10-25",status:"confirmed",place:"Balg nr 3, Torpa",facts:[["Döpt","1848-10-28"],["Födelseförsamling","Torpa"],["Titel","ägare/hemmansägare, läsning behöver verifieras"],["Vigsel","1872-02-22 med Inger Kristina Nilsdotter"],["Källa","Torpa födelsebok 1848 och Torpa AI:3, Bild 69, Sida 27"]],story:["Carl Bengtsson föds 25 oktober 1848 i Torpa och döps 28 oktober.","Födelsenotisen anger honom som son till åbo Bengt Olsson på Balg nr 3 och hustrun Helena Svensdotter.","Som vuxen finns Carl Bengtsson på Balg nr 3 tillsammans med hustrun Inger Kristina Nilsdotter och flera barn, däribland Karl/Carl Karlsson."],parents:["bengt_olsson","helena_svensdotter"],children:["leonard_karlsson","anna_brita_carlsdotter","brita_helena_carlsdotter","karl_karlsson","johan_carlsson"]},
  inger_kristina_nilsdotter:{name:"Inger Kristina Nilsdotter",alt:"Inga Christina Nilsdotter",role:"Karl Karlssons mor",born:"1848-03-03",status:"confirmed",place:"nr 9 Torpa / Balg nr 3, Torpa",facts:[["Döpt","1848-03-05"],["Födelseförsamling","Torpa"],["Tidigare hushållsläsning","1848-03-15 förekommer, korrigerat mot födelsenotis"],["Vigsel","1872-02-22 med Carl Bengtsson"],["Källa","Torpa födelsebok 1848"]],story:["Inger Kristina Nilsdotter föds 3 mars 1848 i Torpa och döps 5 mars.","Födelsenotisen anger henne som dotter till arrendatorn Nils Nilsson på nr 9 Torpa och hustrun Anna Britta Nilsdotter.","Hon återfinns senare på Balg nr 3 tillsammans med maken Carl Bengtsson."],parents:["nils_nilsson_torpa","anna_brita_nilsdotter_torpa"],children:["leonard_karlsson","anna_brita_carlsdotter","brita_helena_carlsdotter","karl_karlsson","johan_carlsson"]},
  leonard_karlsson:{name:"Leonard / Leonhard",role:"Syskon till Karl",born:"1875-11-06",status:"working",place:"Torpa",facts:[["Läsning","Namn och notering behöver verifieras"],["Notering","Överstruken på hushållssidan"]],story:["Leonard eller Leonhard förekommer som son i hushållet med Carl Bengtsson och Inger Kristina Nilsdotter. Namnläsningen behöver verifieras."],parents:["carl_bengtsson","inger_kristina_nilsdotter"],children:[]},
  anna_brita_carlsdotter:{name:"Anna Brita Carlsdotter",role:"Syskon till Karl",born:"1878-02-01",status:"confirmed",place:"Torpa",story:["Anna Brita är dotter till Carl Bengtsson och Inger Kristina Nilsdotter enligt hushållssidan för Balg nr 3."],parents:["carl_bengtsson","inger_kristina_nilsdotter"],children:[]},
  brita_helena_carlsdotter:{name:"Brita Helena Carlsdotter",role:"Syskon till Karl",born:"1881-11-04",status:"confirmed",place:"Torpa",facts:[["Notering","Överstruken på hushållssidan"]],story:["Brita Helena är dotter till Carl Bengtsson och Inger Kristina Nilsdotter enligt hushållssidan för Balg nr 3."],parents:["carl_bengtsson","inger_kristina_nilsdotter"],children:[]},
  johan_carlsson:{name:"Johan Carlsson",role:"Syskon till Karl",born:"1887-11-28",status:"working",place:"Torpa",facts:[["Notering","Namn och utflyttningsnotering behöver verifieras"]],story:["Johan förekommer som son i hushållet med Carl Bengtsson och Inger Kristina Nilsdotter. Namn och eventuell utflyttningsnotering behöver verifieras."],parents:["carl_bengtsson","inger_kristina_nilsdotter"],children:[]},

  bengt_olsson:{name:"Bengt Olsson",role:"Carl Bengtssons far",born:"1816-11-08",status:"confirmed",place:"Balg nr 3, Torpa",facts:[["Döpt","1816-11-10"],["Titel","åbo"],["Avvikande datum","Husförhör/BiS anger 1816-11-07"],["Källa","Torpa födelsebok 1816 och Torpa AI:3, Bild 69, Sida 27"]],story:["Bengt Olsson föds 8 november 1816 i Torpa och döps 10 november. Arbetsdatumet bygger på födelsenotisen, även om husförhör/BiS anger 7 november.","Födelsenotisen anger föräldrarna Olof Berntsson och Hilla Pehrsdotter i Balg.","Som vuxen återfinns Bengt på Balg tillsammans med hustrun Helena Svensdotter och barnen Anna Helena, Johanna Christina och Carl."],parents:["olof_berntsson","hilla_pehrsdotter"],children:["anna_helena_bengtsdotter","johanna_christina_bengtsdotter","carl_bengtsson"]},
  helena_svensdotter:{name:"Helena Svensdotter",role:"Carl Bengtssons mor",born:"1821-04-01",status:"confirmed",place:"Balg nr 3, Torpa",facts:[["Källa","Torpa AI:3 (1835-1849), Bild 69, Sida 27"],["Nästa steg","Bekräfta födelsedatum i födelsebok och identifiera föräldrar"]],story:["Helena Svensdotter är hustru till Bengt Olsson och mor till Carl Bengtsson.","Hon återfinns på Balg i Torpa tillsammans med Bengt och barnen Anna Helena, Johanna Christina och Carl."],parents:[],children:["anna_helena_bengtsdotter","johanna_christina_bengtsdotter","carl_bengtsson"]},
  anna_helena_bengtsdotter:{name:"Anna Helena Bengtsdotter",role:"Syskon till Carl Bengtsson",born:"1844-01-09",status:"confirmed",place:"Balg, Torpa",story:["Anna Helena förekommer som dotter i hushållet med Bengt Olsson och Helena Svensdotter på Balg."],parents:["bengt_olsson","helena_svensdotter"],children:[]},
  johanna_christina_bengtsdotter:{name:"Johanna Christina Bengtsdotter",role:"Syskon till Carl Bengtsson",born:"1846-12-22",status:"confirmed",place:"Balg, Torpa",story:["Johanna Christina förekommer som dotter i hushållet med Bengt Olsson och Helena Svensdotter på Balg."],parents:["bengt_olsson","helena_svensdotter"],children:[]},

  olof_berntsson:{name:"Olof Berntsson",role:"Bengt Olssons far",born:"1783-03-20",status:"confirmed",place:"Balg, Torpa",facts:[["Döpt","1783-03-21"],["Titel","åbo"],["Källa","Torpa födelsebok 1783 och Torpa AI:1 (1806-1826), Bild 85, Sida 130"]],story:["Olof Berntsson föds 20 mars 1783 i Torpa och döps 21 mars.","Födelsenotisen anger föräldrarna Berndt/Bernt Börgesson och Ingeborg Olofsdotter i Balg.","Olof återfinns i hushållet på Balg tillsammans med Hilla Pehrsdotter och barnen Johanna Britta, Kerstin och Bengt."],parents:["bernt_borgesson","ingeborg_olofsdotter"],children:["johanna_britta_olofsdotter","kerstin_olofsdotter","bengt_olsson"]},
  hilla_pehrsdotter:{name:"Hilla Pehrsdotter",role:"Bengt Olssons mor",born:"1784-11-17",status:"confirmed",place:"Balg, Torpa",facts:[["Källa","Torpa AI:1 (1806-1826), Bild 85, Sida 130"],["Nästa steg","Bekräfta födelsedatum i födelsebok och kontrollera vigsel med Olof Berntsson"]],story:["Hilla Pehrsdotter återfinns i hushållet på Balg tillsammans med Olof Berntsson och barnen Johanna Britta, Kerstin och Bengt.","Husförhör/BiS anger födelsedatumet 17 november 1784, vilket ska bekräftas i födelsebok."],parents:[],children:["johanna_britta_olofsdotter","kerstin_olofsdotter","bengt_olsson"]},
  johanna_britta_olofsdotter:{name:"Johanna Britta Olofsdotter",role:"Syskon till Bengt Olsson",born:"1812-09-16",status:"confirmed",place:"Balg, Torpa",story:["Johanna Britta förekommer som dotter i hushållet med Olof Berntsson och Hilla Pehrsdotter på Balg."],parents:["olof_berntsson","hilla_pehrsdotter"],children:[]},
  kerstin_olofsdotter:{name:"Kerstin Olofsdotter",role:"Syskon till Bengt Olsson",born:"1815-04-14",status:"confirmed",place:"Balg, Torpa",story:["Kerstin förekommer som dotter i hushållet med Olof Berntsson och Hilla Pehrsdotter på Balg."],parents:["olof_berntsson","hilla_pehrsdotter"],children:[]},

  borge_borgesson:{name:"Börge Börgesson",alt:"Börjesson",role:"Möjlig far till Berndt",born:"ca 1704",died:"möjl. 1755-11-11",status:"likely",place:"Balg / möjl. Blixtorp, Torpa",facts:[["Vigsel","1753-02-07 med Kierstin/Kerstin Jönsdotter"],["Barn","Bernd/Bernt född 1753-11-28 i Balg, stark kandidat"],["Möjlig dödsnotis","1755-11-11, 51 år och 7 månader, plats osäkert läst som Blixtorp/Blixtorp"],["Status","Stark kandidat, inte slutbevisad"]],story:["Börge Börgesson eller Börjesson är en stark kandidat till far till Berndt/Bernt Börgesson i Balg.","Kandidatkedjan bygger på vigseln 1753-02-07 med Kierstin/Kerstin Jönsdotter och födelsenotisen för sonen Bernd/Bernt, född 1753-11-28 i Balg.","En möjlig dödsnotis 1755 kan passa tidsmässigt, men platsläsningen är osäker och kopplingen ska inte betraktas som bekräftad förrän mantal, dödbok eller andra stödjande källor stärker den."],timeline:[["1753-02-07","Vigs troligen med Kierstin/Kerstin Jönsdotter."],["1753-11-28","Sonen Bernd/Bernt föds i Balg enligt stark kandidatnotis."],["1755-11-11","Möjlig dödsnotis för Börge Börgesson, ännu osäker koppling."]],parents:[],children:["bernt_borgesson"]},
  kierstin_jonsdotter:{name:"Kierstin / Kerstin Jönsdotter",role:"Möjlig mor till Berndt",status:"likely",place:"Balg, Torpa",facts:[["Vigsel","1753-02-07 med Börge Börgesson/Börjesson"],["Barn","Bernd/Bernt född 1753-11-28 i Balg, stark kandidat"],["Status","Stark kandidat, inte slutbevisad"]],story:["Kierstin eller Kerstin Jönsdotter är en stark kandidat till mor till Berndt/Bernt Börgesson i Balg.","Hon kopplas till Börge Börgesson/Börjesson genom vigselnotisen 1753 och till Bernd/Bernt genom födelsenotisen senare samma år. Exakta bild- och siduppgifter behöver fortfarande säkras."],parents:[],children:["bernt_borgesson"]},
  bernt_borgesson:{name:"Berndt / Bernt Börgesson",alt:"Börjesson",role:"Olof Berntssons far",born:"trol. 1753-11-28",status:"confirmed",place:"Balg, Torpa",facts:[["Döpt","troligen 1753-12-02"],["Vigsel","1775-02-19 i Torpa"],["Maka","Ingeborg Olofsdotter"],["Möjliga föräldrar","Börge Börgesson/Börjesson och Kierstin/Kerstin Jönsdotter i Balg"],["Namnnotering","Vigselnotisen skriver Börgesson, ArkivDigital normerar till Börjesson"],["Källa","Torpa CI:1 (1691-1810), Bild 650, Sida 125 samt Torpa födelsebok 1753, exakt bild/sida behöver anges"]],story:["Berndt eller Bernt Börgesson vigs 19 februari 1775 i Torpa med pigan Ingeborg Olofsdotter från Stomgården.","Han anges som dräng i Balg. Paret får barnen Bengt, Kirstin, Johanna och Olof i Balg mellan 1776 och 1783.","En stark kandidat till hans egen födelse finns i Torpa 1753: Bernd/Bernt, född 28 november och döpt 2 december i Balg, son till Börge Börgesson/Börjesson och Kierstin/Kerstin Jönsdotter. Kopplingen är mycket rimlig men bör fortsatt stärkas med dödsnotis, mantal eller ytterligare fadder-/syskonkopplingar.","Faddermaterialet pekar mot återkommande kopplingar i Balg och Torpa, särskilt Karin Börgesdotter och Jöns Börgesson som möjliga släktspår."],timeline:[["trol. 1753-11-28","Stark kandidat föds i Balg, Torpa."],["1775-02-19","Vigs med Ingeborg Olofsdotter från Stomgården."],["1776-01-18","Sonen Bengt föds i Balg."],["1778-11-23","Dottern Kirstin föds i Balg."],["1782-01-02","Dottern Johanna föds i Balg."],["1783-03-20","Sonen Olof föds i Balg."]],parents:["borge_borgesson","kierstin_jonsdotter"],children:["bengt_berntsson","kirstin_berntsdotter","johanna_berntsdotter","olof_berntsson"]},
  ingeborg_olofsdotter:{name:"Ingeborg Olofsdotter",role:"Olof Berntssons mor",status:"confirmed",place:"Stomgården / Balg, Torpa",facts:[["Vigsel","1775-02-19 i Torpa"],["Hemort vid vigsel","Stomgården"],["Make","Berndt/Bernt Börgesson/Börjesson"],["Barn","Bengt, Kirstin, Johanna och Olof"],["Källa","Torpa CI:1 (1691-1810), Bild 650, Sida 125"]],story:["Ingeborg Olofsdotter anges vid vigseln 1775 som piga från Stomgården. Efter vigseln kopplas hon till Balg tillsammans med Berndt/Bernt Börgesson.","Hon är mor till barnen Bengt, Kirstin, Johanna och Olof Berntsson/Olofsdotter, födda i Balg mellan 1776 och 1783.","Hennes ursprung före vigseln från Stomgården är ett viktigt fortsatt forskningsspår."],parents:[],children:["bengt_berntsson","kirstin_berntsdotter","johanna_berntsdotter","olof_berntsson"]},
  bengt_berntsson:{name:"Bengt Berntsson",role:"Syskon till Olof Berntsson",born:"1776-01-18",status:"confirmed",place:"Balg, Torpa",facts:[["Döpt","1776-01-21"],["Källa","Torpa CI:1, Bild 720, Sida 139"],["Faddrar","Bland andra Anders Olofsson i Torpa Tolsgård/Tolfsgård, Hindrich Larsson i Balg, Erik Nilsson i Balg och Karin Börgesdotter i Torpa Tolsgård/Tolfsgård; flera läsningar är preliminära"]],story:["Bengt föds 18 januari 1776 i Balg som barn till Berndt/Bernt Börgesson och Ingeborg Olofsdotter.","Faddrarna är viktiga för att förstå nätverket kring Balg. Karin Börgesdotter är särskilt intressant eftersom patronymikonet kan tyda på släktkoppling till Berndt/Bernt."],parents:["bernt_borgesson","ingeborg_olofsdotter"],children:[]},
  kirstin_berntsdotter:{name:"Kirstin Berntsdotter",role:"Syskon till Olof Berntsson",born:"1778-11-23",status:"confirmed",place:"Balg, Torpa",facts:[["Döpt","1778-11-23"],["Källa","Torpa CI:1, Bild 780, Sida 151"],["Faddrar","Bland andra Anders Svensson i Balg, Pähr Andersson i Balg, Lars Larsson i Balg, Pernilla Olofsdotter i Torpa, Hilla Eliasdotter i Torpa och Ingegärd Mathisdotter i Balg"]],story:["Kirstin föds och döps 23 november 1778 i Balg som dotter till Berndt/Bernt Börgesson och Ingeborg Olofsdotter.","Fadderlistan stärker bilden av ett tätt Balg-/Torpa-nätverk som behöver följas vidare."],parents:["bernt_borgesson","ingeborg_olofsdotter"],children:[]},
  johanna_berntsdotter:{name:"Johanna Berntsdotter",role:"Syskon till Olof Berntsson",born:"1782-01-02",status:"confirmed",place:"Balg, Torpa",facts:[["Döpt","1782-01-03"],["Källa","Torpa CI:1, Bild 910, Sida 177"],["Faddrar","Bland andra Jöns Börgesson i Torpa, Anders Hellersson/Hallersson i Gunnestorp, Kirstin Olofsdotter i Balg, Anna Larsdotter i Balg och Anna Andersdotter i Balg; flera läsningar är preliminära"]],story:["Johanna föds 2 januari 1782 i Balg som dotter till Berndt/Bernt Börgesson och Ingeborg Olofsdotter.","Faddern Jöns Börgesson är särskilt intressant eftersom han kan vara bror eller nära släkting till Berndt/Bernt, men detta är ännu inte bevisat."],parents:["bernt_borgesson","ingeborg_olofsdotter"],children:[]},
  jons_borgesson:{name:"Jöns Börgesson",role:"Kandidatspår vid Balg",status:"working",place:"Balg / Torpa Stomgård",facts:[["Vigsel","1777-12-22 med Petronella Olofsdotter"],["Hemort","Dräng från Balg"],["Koppling","Förekommer som fadder i Berndt/Bernts familj"],["Status","Sidospår, släktskap ej bevisat"]],story:["Jöns Börgesson är ett viktigt sidospår eftersom han förekommer som fadder i familjen Berndt/Bernt Börgesson och Ingeborg Olofsdotter.","Han vigs 22 december 1777 som dräng från Balg med pigan Petronella Olofsdotter, möjligen från Torpa Stomgård. Kopplingen till både Balg och Stomgården gör honom intressant, men släktskapet är ännu inte bevisat."],parents:[],children:[]},
  petronella_olofsdotter:{name:"Petronella Olofsdotter",role:"Kandidatspår vid Stomgården",status:"working",place:"Torpa Stomgård",facts:[["Vigsel","1777-12-22 med Jöns Börgesson"],["Status","Sidospår, möjlig Stomgården-koppling behöver verifieras"]],story:["Petronella Olofsdotter vigs 1777 med Jöns Börgesson från Balg. Hennes hemort läses preliminärt som Torpa Stomgård eller Stomg.","Eftersom Ingeborg Olofsdotter också kom från Stomgården är Petronella ett intressant kontrollspår, men någon släktkoppling är ännu inte bevisad."],parents:[],children:[]},
  nils_nilsson_torpa:{name:"Nils Nilsson",role:"Inger Kristinas far",status:"confirmed",place:"nr 9 Torpa",facts:[["Titel","arrendator"],["Maka","Anna Britta Nilsdotter"],["Källa","Födelsenotis för Inger Kristina Nilsdotter, 1848-03-03"]],story:["Nils Nilsson är far till Inger Kristina Nilsdotter enligt hennes födelsenotis 1848.","Han anges som arrendator på nr 9 Torpa. Hans eget födelsedatum och föräldrar är ännu inte kartlagda."],parents:[],children:["inger_kristina_nilsdotter"]},
  anna_brita_nilsdotter_torpa:{name:"Anna Britta Nilsdotter",role:"Inger Kristinas mor",status:"confirmed",place:"nr 9 Torpa",facts:[["Make","Nils Nilsson"],["Källa","Födelsenotis för Inger Kristina Nilsdotter, 1848-03-03"]],story:["Anna Britta Nilsdotter är mor till Inger Kristina Nilsdotter enligt födelsenotisen 1848.","Familjen är kopplad till nr 9 Torpa. Hennes eget födelsedatum och föräldrar är ännu inte kartlagda."],parents:[],children:["inger_kristina_nilsdotter"]},
  axel_nilsson:{name:"Axel Nilsson",born:"1996-01-03",status:"confirmed",role:"Bygger trädet",story:["Axel Nilsson föds 3 januari 1996, barn till Gerd Bengtsson och Göran Nilsson. Det är Axel som bygger detta släktträd."],parents:["gerd_bengtsson","goran_nilsson"],children:[]},
  ebba_nilsson:{name:"Ebba Nilsson",born:"1998-05-26",status:"confirmed",role:"Syskon",story:["Ebba Nilsson föds 26 maj 1998, barn till Gerd Bengtsson och Göran Nilsson."],parents:["gerd_bengtsson","goran_nilsson"],children:[]}
};

const UNITS = [
  {id:"u_lars_inger",gen:0,persons:["lars_esbjornsson","inger_jonsdotter"],ancestor:true,children:["u_carl_bengta"]},
  {id:"u_arvid_elin",gen:0,persons:["arvid_svensson","elin_bengtsdotter"],ancestor:true,children:["u_hans","u_anders_arfvid","u_inger_arfvid","u_bengt_arfvid","u_nils_arfvid","u_carl_bengta"]},
  {id:"u_borge_kierstin",gen:0,persons:["borge_borgesson","kierstin_jonsdotter"],ancestor:true,children:["u_bernt_ingeborg"]},
  {id:"u_jons_petronella",gen:0,persons:["jons_borgesson","petronella_olofsdotter"],ancestor:true,children:[]},
  {id:"u_bernt_ingeborg",gen:1,persons:["bernt_borgesson","ingeborg_olofsdotter"],ancestor:true,children:["u_bengt_berntsson","u_kirstin_berntsdotter","u_johanna_berntsdotter","u_olof_hilla"]},
  {id:"u_hans",gen:1,persons:["hans_arfvidsson"],children:[]},
  {id:"u_anders_arfvid",gen:1,persons:["anders_arfvidsson"],children:[]},
  {id:"u_inger_arfvid",gen:1,persons:["inger_arfvidsdotter"],children:[]},
  {id:"u_bengt_arfvid",gen:1,persons:["bengt_arfvidsson"],children:[]},
  {id:"u_nils_arfvid",gen:1,persons:["nils_arfvidsson"],children:[]},
  {id:"u_bengt_berntsson",gen:2,persons:["bengt_berntsson"],children:[]},
  {id:"u_kirstin_berntsdotter",gen:2,persons:["kirstin_berntsdotter"],children:[]},
  {id:"u_johanna_berntsdotter",gen:2,persons:["johanna_berntsdotter"],children:[]},
  {id:"u_olof_hilla",gen:2,persons:["olof_berntsson","hilla_pehrsdotter"],heir:true,children:["u_johanna_britta_olofs","u_kerstin_olofs","u_bengt_helena"]},
  {id:"u_carl_bengta",gen:1,persons:["carl_larsson","bengta_arvidsdotter"],heir:true,children:["u_anders_johanna","u_nils_carl","u_anna_lena"]},
  {id:"u_johanna_britta_olofs",gen:3,persons:["johanna_britta_olofsdotter"],children:[]},
  {id:"u_kerstin_olofs",gen:3,persons:["kerstin_olofsdotter"],children:[]},
  {id:"u_bengt_helena",gen:3,persons:["bengt_olsson","helena_svensdotter"],heir:true,children:["u_anna_helena_bengts","u_johanna_christina_bengts","u_carl_inger_kristina"]},
  {id:"u_nils_anna_brita",gen:3,persons:["nils_nilsson_torpa","anna_brita_nilsdotter_torpa"],ancestor:true,children:["u_carl_inger_kristina"]},
  {id:"u_nils_carl",gen:2,persons:["nils_carlsson"],children:[]},
  {id:"u_anna_lena",gen:2,persons:["anna_lena_carlsdotter"],children:[]},
  {id:"u_anna_helena_bengts",gen:4,persons:["anna_helena_bengtsdotter"],children:[]},
  {id:"u_johanna_christina_bengts",gen:4,persons:["johanna_christina_bengtsdotter"],children:[]},
  {id:"u_carl_inger_kristina",gen:4,persons:["carl_bengtsson","inger_kristina_nilsdotter"],heir:true,children:["u_leonard","u_anna_brita_carls","u_brita_helena","u_karl_elemina","u_johan_carlsson"]},
  {id:"u_anders_johanna",gen:2,persons:["anders_carlsson","johanna_svensdotter"],heir:true,children:["u_lars_august","u_sven_johan","u_christina","u_bengt_aron","u_johan_britta"]},
  {id:"u_lars_august",gen:3,persons:["lars_august"],children:[]},
  {id:"u_sven_johan",gen:3,persons:["sven_johan_andersson"],children:[]},
  {id:"u_christina",gen:3,persons:["christina_andersdotter"],children:[]},
  {id:"u_bengt_aron",gen:3,persons:["bengt_aron_andersson"],children:[]},
  {id:"u_johan_britta",gen:3,persons:["johan_andersson","britta_lovisa"],heir:true,children:["u_augusta","u_birger","u_jenny","u_karl_ester"]},
  {id:"u_leonard",gen:5,persons:["leonard_karlsson"],children:[]},
  {id:"u_anna_brita_carls",gen:5,persons:["anna_brita_carlsdotter"],children:[]},
  {id:"u_brita_helena",gen:5,persons:["brita_helena_carlsdotter"],children:[]},
  {id:"u_karl_elemina",gen:5,persons:["karl_karlsson","elemina_karlsdotter"],heir:true,children:["u_nils_lennart","u_ingrid_svea","u_elsa_helena","u_karin_linnea","u_sonja_ingeborg"]},
  {id:"u_johan_carlsson",gen:5,persons:["johan_carlsson"],children:[]},
  {id:"u_augusta",gen:4,persons:["augusta_charlotta"],children:[]},
  {id:"u_birger",gen:4,persons:["birger_johansson"],children:[]},
  {id:"u_jenny",gen:4,persons:["jenny_johansson"],children:[]},
  {id:"u_karl_ester",gen:4,persons:["karl_hjalmar_johansson","ester_viktoria"],heir:true,children:["u_asta","u_elsa","u_karin_harry","u_erik","u_gosta","u_uno","u_sjunne"]},
  {id:"u_nils_lennart",gen:6,persons:["nils_lennart_karlsson"],children:[]},
  {id:"u_ingrid_svea",gen:6,persons:["ingrid_svea_viola_karlsson"],children:[]},
  {id:"u_elsa_helena",gen:6,persons:["elsa_helena_karlsson"],heir:true,children:["u_gerd_goran"]},
  {id:"u_karin_linnea",gen:6,persons:["karin_linnea_karlsson"],children:[]},
  {id:"u_sonja_ingeborg",gen:6,persons:["sonja_ingeborg_karlsson"],children:[]},
  {id:"u_asta",gen:5,persons:["asta_linnea"],children:[]},
  {id:"u_elsa",gen:5,persons:["elsa_ingegerd"],children:[]},
  {id:"u_karin_harry",gen:5,persons:["karin_margit","harry_bengtsson"],heir:true,children:["u_ingemar","u_gerd_goran"]},
  {id:"u_erik",gen:5,persons:["erik_bertil"],children:[]},
  {id:"u_gosta",gen:5,persons:["gosta_ingemar"],children:[]},
  {id:"u_uno",gen:5,persons:["karl_john_uno"],children:[]},
  {id:"u_sjunne",gen:5,persons:["sjunne_lennart"],children:[]},
  {id:"u_ingemar",gen:6,persons:["ingemar_bengtsson"],children:[]},
  {id:"u_gerd_goran",gen:7,persons:["gerd_bengtsson","goran_nilsson"],heir:true,children:["u_axel","u_ebba"]},
  {id:"u_axel",gen:8,persons:["axel_nilsson"],heir:true,children:[]},
  {id:"u_ebba",gen:8,persons:["ebba_nilsson"],children:[]}
];

const EDGES = UNITS.flatMap(unit => (unit.children||[]).map(child => ({from:unit.id,to:child})));
const DIRECT_HEIRS = new Set(["lars_esbjornsson","inger_jonsdotter","arvid_svensson","elin_bengtsdotter","carl_larsson","bengta_arvidsdotter","anders_carlsson","johan_andersson","karl_hjalmar_johansson","karin_margit","gerd_bengtsson","goran_nilsson","elsa_helena_karlsson","karl_karlsson","elemina_karlsdotter","carl_bengtsson","inger_kristina_nilsdotter","bengt_olsson","helena_svensdotter","olof_berntsson","hilla_pehrsdotter","bernt_borgesson","ingeborg_olofsdotter","borge_borgesson","kierstin_jonsdotter","nils_nilsson_torpa","anna_brita_nilsdotter_torpa","axel_nilsson"]);
const DIRECT_UNITS = new Set(["u_lars_inger","u_arvid_elin","u_carl_bengta","u_anders_johanna","u_johan_britta","u_karl_ester","u_karin_harry","u_gerd_goran","u_axel","u_borge_kierstin","u_bernt_ingeborg","u_olof_hilla","u_bengt_helena","u_nils_anna_brita","u_carl_inger_kristina","u_karl_elemina","u_elsa_helena"]);
const DIRECT_EDGES = new Set([
  "u_lars_inger>u_carl_bengta",
  "u_arvid_elin>u_carl_bengta",
  "u_carl_bengta>u_anders_johanna",
  "u_anders_johanna>u_johan_britta",
  "u_johan_britta>u_karl_ester",
  "u_karl_ester>u_karin_harry",
  "u_karin_harry>u_gerd_goran",
  "u_borge_kierstin>u_bernt_ingeborg",
  "u_bernt_ingeborg>u_olof_hilla",
  "u_olof_hilla>u_bengt_helena",
  "u_bengt_helena>u_carl_inger_kristina",
  "u_nils_anna_brita>u_carl_inger_kristina",
  "u_carl_inger_kristina>u_karl_elemina",
  "u_karl_elemina>u_elsa_helena",
  "u_elsa_helena>u_gerd_goran",
  "u_gerd_goran>u_axel"
]);
const MOTHER_UNITS = new Set(["u_lars_inger","u_arvid_elin","u_hans","u_anders_arfvid","u_inger_arfvid","u_bengt_arfvid","u_nils_arfvid","u_carl_bengta","u_nils_carl","u_anna_lena","u_anders_johanna","u_lars_august","u_sven_johan","u_christina","u_bengt_aron","u_johan_britta","u_augusta","u_birger","u_jenny","u_karl_ester","u_asta","u_elsa","u_karin_harry","u_erik","u_gosta","u_uno","u_sjunne","u_ingemar"]);
const FATHER_UNITS = new Set(["u_borge_kierstin","u_jons_petronella","u_bernt_ingeborg","u_bengt_berntsson","u_kirstin_berntsdotter","u_johanna_berntsdotter","u_olof_hilla","u_johanna_britta_olofs","u_kerstin_olofs","u_bengt_helena","u_nils_anna_brita","u_anna_helena_bengts","u_johanna_christina_bengts","u_carl_inger_kristina","u_leonard","u_anna_brita_carls","u_brita_helena","u_karl_elemina","u_johan_carlsson","u_nils_lennart","u_ingrid_svea","u_elsa_helena","u_karin_linnea","u_sonja_ingeborg"]);
const UNIT_BY_ID = Object.fromEntries(UNITS.map(u=>[u.id,u]));
const PERSON_TO_UNIT = {};
UNITS.forEach(u=>u.persons.forEach(pid=>{ if(!PERSON_TO_UNIT[pid]) PERSON_TO_UNIT[pid]=u.id; }));
const PARTNER = {};
UNITS.filter(u=>u.persons.length>1).forEach(u=>{ PARTNER[u.persons[0]]=u.persons[1]; PARTNER[u.persons[1]]=u.persons[0]; });

const PLACES = [
  { id:"tvaaker", name:"Tvååker", area:"Halland", lat:57.041, lng:12.400, zoom:12, aliases:["Tvååker"], note:"Socknen där flera centrala händelser i Carl-, Bengta- och Anders-ledet finns." },
  { id:"ronas", name:"Rönås", area:"Tvååker", lat:57.044, lng:12.394, zoom:14, aliases:["Rönås"], note:"Kopplat till Carl Larsson, Bengta Arvidsdotter och Anders Carlsson." },
  { id:"munkaskog", name:"Munkaskog", area:"Tvååker", lat:57.032, lng:12.410, zoom:14, aliases:["Munkaskog","Sven Börges gård","Sven Börjes gård","Svenborgsgård","Sven Börs"], note:"Central plats för Arfvid Svensson, Elin Bengtsdotter och Bengta Arvidsdotter." },
  { id:"munkagard", name:"Munkagård", area:"Tvååker", aliases:["Munkagård"], note:"Förekommer i det geografiska klustret. Exakt koppling och kartläge kan fyllas på när källorna blir tydligare." },
  { id:"smedsgard", name:"Smedsgård", area:"Tvååker", aliases:["Smedsgård"], note:"Förekommer i det geografiska klustret. Exakt koppling och kartläge kan fyllas på när källorna blir tydligare." },
  { id:"vraen", name:"Wråen / Vråen / Wräen", area:"Tvååker", lat:57.039, lng:12.424, zoom:14, aliases:["Wråen","Vråen","Wräen","Lilla Wråen"], note:"Förekommer i Anders Carlssons arbets- och flyttspår." },
  { id:"agard", name:"Ågård", area:"Tvååker", lat:57.050, lng:12.372, zoom:14, aliases:["Ågård"], note:"Kopplas till Carl Larsson i senare liv och dödnotis." },
  { id:"galtaback", name:"Galtabäck", area:"Tvååker", lat:57.017, lng:12.336, zoom:13, aliases:["Galtabäck"], note:"Ingår i det geografiska klustret kring Tvååker." },
  { id:"tagebo", name:"Tagebo", area:"Tvååker", aliases:["Tagebo"], note:"Förekommer i det geografiska klustret. Exakt koppling och kartläge kan fyllas på när källorna blir tydligare." },
  { id:"ledsgard", name:"Ledsgård", area:"Tvååker", aliases:["Ledsgård"], note:"Förekommer i det geografiska klustret. Exakt koppling och kartläge kan fyllas på när källorna blir tydligare." },
  { id:"hermanslycka", name:"Hermanslycka", area:"Tvååker", aliases:["Hermanslycka"], note:"Förekommer i det geografiska klustret. Exakt koppling och kartläge kan fyllas på när källorna blir tydligare." },
  { id:"grimeton", name:"Grimeton", area:"Halland", lat:57.108, lng:12.425, zoom:12, aliases:["Grimeton"], note:"Sockenområde för Carls födelsespår." },
  { id:"tjarby", name:"Tjärby", area:"Grimeton", lat:57.104, lng:12.459, zoom:14, aliases:["Tjärby"], note:"Födelseplats för Carl Larsson." },
  { id:"morup", name:"Morup", area:"Halland", lat:56.994, lng:12.392, zoom:12, aliases:["Morup"], note:"Kopplat till Karl Hjalmar Johansson och Karin Margit Johansson." },
  { id:"morups_prastgard", name:"Morups Prästgård", area:"Morup", aliases:["Morups Prästgård"], note:"Senare boendemiljö för Johan Andersson enligt arbetsmaterialet. Exakt kartläge kan läggas till senare." },
  { id:"skillingshagen", name:"Skillingshagen", area:"Morup", lat:56.997, lng:12.383, zoom:14, aliases:["Skillingshagen","Morup No 5"], note:"Hushållsplats i Morup-ledet." },
  { id:"klastorp", name:"Klastorp", area:"Åttabro / Varberg centrum", lat:57.114, lng:12.292, zoom:15, aliases:["Klastorp"], note:"Karin och Harry flyttar hit enligt familjeuppgift. Markören är korrigerad till ungefär Åttabro vid trafikplats Varberg centrum." },
  { id:"attabro", name:"Åttabro", area:"Varberg", lat:57.114, lng:12.292, zoom:15, aliases:["Åttabro"], note:"Område vid trafikplats Varberg centrum. Används som ungefärligt läge för Klastorp-markören tills exaktare läge finns." },
  { id:"varberg_centrum", name:"Varberg centrum", area:"Varberg", lat:57.105, lng:12.251, zoom:13, aliases:["Varberg centrum"], note:"Modern orienteringspunkt för Klastorp/Åttabro-området." },
  { id:"grytas", name:"Grytås", area:"Halland", lat:57.032, lng:12.455, zoom:13, aliases:["Grytås"], note:"Johan Andersson står som dräng i Grytås vid vigseln 1874." },
  { id:"langas", name:"Långås", area:"Halland", lat:56.976, lng:12.470, zoom:13, aliases:["Långås","Långås No 3"], note:"Möjligt vigsel-/tjänstespår för Britta Lovisa Carlsdotter." },
  { id:"torpa_n", name:"Torpa (N)", area:"Halland", lat:57.202, lng:12.285, zoom:13, aliases:["Torpa","Torpa (N)"], note:"Central församling på Göran Nilssons morslinje. Markören är ungefärligt satt i Torpa-området tills exaktare socken-/kyrkpunkt är verifierad." },
  { id:"balg", name:"Balg", area:"Torpa", lat:57.201, lng:12.298, zoom:15, aliases:["Balg","Balg nr 3","Balg/Bälg nr 3","Bälg nr 3"], note:"Huvudplats på fars sida. Kopplad till Elsa Helena, Karl Karlsson, Carl Bengtsson, Bengt Olsson, Olof Berntsson, Berndt/Bernt Börgesson och äldre Balg-spår. Markören är preliminär." },
  { id:"torpa_nr_9", name:"nr 9 Torpa", area:"Torpa", lat:57.197, lng:12.290, zoom:15, aliases:["nr 9 Torpa","No 9 Torpa"], note:"Plats för Nils Nilsson och Anna Britta Nilsdotter i Inger Kristina Nilsdotters födelsenotis 1848. Markören är preliminär." },
  { id:"as", name:"Ås", area:"Halland", lat:57.235, lng:12.210, zoom:13, aliases:["Ås"], note:"Födelseförsamling för Elemina Karlsdotter och Nils Lennart Karlsson enligt farsidans arbetsmaterial. Markören är ungefärligt satt i Ås/Åskloster-området." },
  { id:"aby", name:"Åby", area:"Halland", lat:57.219, lng:12.265, zoom:13, aliases:["Åby"], note:"Familjen Karl Karlsson och Elemina Karlsdotter verkar ha flyttat via Åby omkring 1916. Markören är preliminär och behöver verifieras mot rätt Åby i källorna." },
  { id:"stomgarden", name:"Stomgården", area:"Torpa", lat:57.194, lng:12.278, zoom:15, aliases:["Stomgården","Torpa Stomgård","Stomg"], note:"Ingeborg Olofsdotter anges som piga från Stomgården vid vigseln 1775 med Berndt/Bernt Börgesson. Petronella Olofsdotter har en möjlig Stomgården-koppling i Jöns Börgesson-spåret. Markören är preliminär." },
  { id:"torpa_tolsgard", name:"Torpa Tolsgård / Tolfsgård", area:"Torpa", aliases:["Torpa Tolsgård","Torpa Tolfsgård","Tolsgård","Tolfsgård"], note:"Preliminär fadderplats i Berndt/Bernt Börgessons familj. Gårdsläsningen behöver kontrolleras mot originalbild." },
  { id:"gunnestorp", name:"Gunnestorp", area:"Torpa", aliases:["Gunnestorp"], note:"Preliminär fadderplats i Johanna Berntsdotters födelsenotis 1782. Läsningen Anders Hellersson/Hallersson i Gunnestorp behöver kontrolleras." },
  { id:"kjerra_karra", name:"Kjerra / Kärra", area:"Torpa", aliases:["Kjerra","Kärra"], note:"Preliminär fadderplats i Olof Berntssons födelsenotis 1783. Ort- och namnläsningar behöver kontrolleras." },
  { id:"blixtorp", name:"Blixtorp", area:"Torpa", aliases:["Blixtorp","Blixtorp?"], note:"Möjlig plats i en osäker dödsnotis 1755 för Börge Börgesson. Kopplingen till Balg-familjen är inte bekräftad." }
];
